#version: '3.8'
#
#services:
#  app:
#    build: .
#    ports:
#      - "8084:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/app_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_PROFILES_ACTIVE: dev
#
#  db:
#    image: postgres:14
#    environment:
#      POSTGRES_DB: app_db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data: